---
kind: pipeline
type: docker
name: build_image

steps:
- name: publish
  image: plugins/docker
  privileged: true
  settings:
    repo: haylinmoore/drone-image-optimizer
    tags: latest
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
